Show UserError message when electronic mail template is incorrect. Ti…
NaN-tic/trytond-electronic_mail_template pull request #1
Opened 2021-04-13 11:50 UTC by MarinaNico

…cket 043403

2021-04-14 22:46 UTC, albertca requested changes

2021-04-14 22:46 UTC, albertca commented on template.py
> +        generate = None
No necessites aquesta línia.

2021-04-14 22:46 UTC, albertca commented on message.xml
> +      <record model="ir.message" id="recipients_error">
Ja que canviem la tabulació fem 4 espais extra, enlloc de 2.

2021-04-15 21:05 UTC, albertca approved these changes

2021-04-15 21:05 UTC, albertca commented on template.py
> +            generate = template.generate(**template_context).render(
No need for a "generate" variable. You can return here.

2021-04-29 14:38 UTC, raimonesteve approved these changes
LGTM amb locales

2021-04-29 14:38 UTC, raimonesteve commented on message.xml
> +        <record model="ir.message" id="recipients_error">
Faltarien els locales. Fer nou commit amb locales o incloure'ls amb aquest

2021-04-29 17:29 UTC, merged